services:
  web: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:     
      - database
      - redis
      - webpacker
    ports: 
      - "3000:3000"
    volumes:
      - .:/enc2
      - bundler_gems:/usr/local/bundle/
    env_file: .env

  database:
    image: postgres:13.7
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"
    env_file:
      - '.env'

  redis:
    image: redis
    ports:
      - "6379"
    env_file:
      - '.env'
    volumes:
      - enc2_redis_data:/data
 
  sidekiq:
    build:
      context: .
    volumes:
      - .:/enc2
    command: /bin/bash -l -c "bundle exec sidekiq -C config/sidekiq.yml"
    depends_on:
      - database
      - redis
    env_file:
      - '.env'

  webpacker:
    build: .
    volumes:
      - .:/enc2
      - enc2_bundler:/usr/local/bundle
    ports:
      - '3035:3035'
    entrypoint: ./entrypoints/webpacker-entrypoint.sh
  
volumes:
  db_data:
  enc2_redis_data: 
  enc2_bundler:   
  bundler_gems:
