FROM node:16-alpine

# Create app directory
WORKDIR /enc2

# Install app dependencies
COPY package*.json yarn.lock ./
RUN yarn install --frozen-lockfile

RUN npm install

#To be removed CMD yarn start, yarn dev

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]
