services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -l -c "bundle exec rails s -p 3000 -b '0.0.0.0'" 
    depends_on:     
      - database
      - redis
      - webpack
    ports: 
      - "3000:3000"
    volumes:
      - .:/enc2
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    restart: always
    image: redis
    ports:
      - "6379"
    env_file:
      - '.env'
    volumes:
      - enc2_redis_data:/data

  webpack:
    build: .
    command: ./bin/webpack-dev-server --inline true
    volumes:
      - '.:/enc2'
    ports:
      - '3035:3035'

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web      
      - database
      - redis
    volumes:
      - .:/enc2
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  enc2_redis_data:     
