#!/bin/sh

set -e

if [ -f /app/tmp/pids/server.pid ]; then
  rm /app/tmp/pids/server.pid
fi

#bin/bash -l -c bundle exec rake db:migrate && /bin/bash -l -c bundle exec rake db:setup && /bin/bash -l -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
#exec bunle
exec "$@"
